[project]
name = "items-service"
version = "0.1.0"
description = "Manage items"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "flask==3.0.0",
    "flask-openapi3[swagger]==4.3.2",
    "pydantic==2.13.5",
    "pymysql==1.1.0",
    "pytest==9.0.3",
    "python-dotenv==1.0.0",
    "requests==2.31.0",
]
